<a href="https://colab.research.google.com/github/arjunakula/Colab-Pytorch/blob/master/PyTorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

hw12 = '%s - %s - %d' % ('hello', 'world', 12)

In [0]:
print(hw12)

hello - world - 12


In [0]:
x = range(5)

In [0]:
print(x)

range(0, 5)


In [0]:
print(list(x))

[0, 1, 2, 3, 4]


In [0]:
s = 'abc'
it = iter(s)
it

In [0]:
next(it)

'a'

In [0]:
x = [1,2,3]
next(iter(x))


1

In [0]:
next(iter(x))

1

In [0]:
it = iter(x)


In [0]:
next(it)

1

In [0]:
next(it)

2

In [0]:
next(it)

3

In [0]:
next(it)

StopIteration: ignored

In [0]:
import numpy as np

In [0]:
np.ones(1)

array([1.])

In [0]:
np.ones([1,2])


array([[1., 1.]])

In [0]:
np.ones((1,2))

array([[1., 1.]])

In [0]:
np.ones(1,2)


TypeError: ignored

In [0]:
np.ones(2,dtype='int32')

array([1, 1], dtype=int32)

In [0]:
x = np.array([[1,2,3],[4,5,6]])

In [0]:
x



array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
x = np.array([[1,2,3],[4,5,6]],dtype=np.float64)

In [0]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
x = np.array([[1,2,3],[4,5,6]],dtype='float64')

In [0]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])